export const Workers = 'Workers'
export const Name = 'Name'
export const HeapUse = 'Heap use'
export const Unavailable = 'Unavailable'
export const NoWorkersAreRunning = 'No workers are running.'
export const TerminateWorker = 'Terminate Worker'
export const TakeHeapSnapshot = 'Take Heap Snapshot'
